@startuml
interface DataContainerInterface <BaseDataSetInterface> {
  +get_train_data(): BaseDataSetInterface
  +get_test_data(): BaseDataSetInterface
  +get_validation_data(): BaseDataSetInterface
  +get_all_data(): BaseDataSetInterface
}

class DataContainer <BaseDataSetInterface> {
}
DataContainerInterface <|.. DataContainer : implements

@enduml
