@startuml

interface SplittableDataInterface {
  +get_train_data(): ReformattableDataInterface
  +get_test_data(): ReformattableDataInterface
  +get_validation_data(): ReformattableDataInterface
  +get_all_data(): ReformattableDataInterface
}

interface ReformattableDataInterface {
  +<<create>>from_format(format: BaseDataFormat)
  +to_format(format: BaseDataFormat)
  +get_storage_format()
  +persist()
}

ReformattableDataInterface <|-- StructuredDataInterface
ReformattableDataInterface <|-- SemiStructuredDataInterface
ReformattableDataInterface <|-- FileDataInterface

interface StructuredDataInterface {
  +<<create>>from_format(format: StructuredDataFormat)
  +to_format(format: StructuredDataFormat)
}

interface SemiStructuredDataInterface {
  +<<create>>from_format(format: SemiStructuredDataFormat)
  +to_format(format: SemiStructuredDataFormat)
}

interface FileDataInterface {
  +<<create>>from_format(format: FileFormat)
  +to_format(format: FileFormat)
}

@enduml
