@startuml

interface BaseDataContainerInterface {
  +<<create>>from_subsets()
  +<<create>>from_complete_set()

  +get_train_data(): BaseDataSetInterface
  +get_test_data(): BaseDataSetInterface
  +get_validation_data(): BaseDataSetInterface
  +get_all_data(): BaseDataSetInterface
}

class BaseDataContainer
BaseDataContainerInterface <|.. BaseDataContainer : implements

interface BaseDataSetInterface{
  +<<create>>from_format(format: BaseDataFormat)

  +to_format(format: BaseDataFormat)
  +get_storage_format()
  +persist()
}


BaseDataContainerInterface ..|> BaseDataSetInterface: uses (get_*_data() returns instances that implement BaseDataSetInterface)

@enduml
