@startuml


abstract class BaseDataContainer {
  +<<create>>from_format(format: BaseDataFormat)
  +to_format(format: BaseDataFormat)
  +get_storage_format()
  +persist()
  - splitter: BaseDataSplitter
}

abstract class BaseDataSplitter {
  - test_proportion: float = 0.2
  - validation_proportion: float = 0.2
  - _split_data()
  + get_train_data()
  + get_test_data()
  + get_validation_data()
}

class IndependentDataSplitter
class TimeSeriesDataSplitter {
  - time_identifiers
}

class ClusteredDataSplitter {
  - cluster_identifiers
}

class SpatialDataSplitter {
  - coordinate_identifiers
}

class PreSplitDataSplitter{
  - training_set
  - validation_set
  - test_set
  - _split_data(): SemanticError
  + combine_data()
}

BaseDataSplitter <|-- IndependentDataSplitter
BaseDataSplitter <|-- TimeSeriesDataSplitter
BaseDataSplitter <|-- ClusteredDataSplitter
BaseDataSplitter <|-- SpatialDataSplitter
BaseDataSplitter <|-- PreSplitDataSplitter

abstract class BaseDataSet {
  +<<create>>from_format(format: BaseDataFormat)
  +to_format(format: BaseDataFormat)
  +get_storage_format()
  +persist()
}

BaseDataContainer o-- BaseDataSplitter : has a (delegates to)
BaseDataContainer ..|> BaseDataSet : uses (can return)

class StructuredDataSet{
  +<<create>>from_format(format: StructuredDataFormat)
  +to_format(format: StructuredDataFormat)
}

class SemiStructuredDataSet{
  +<<create>>from_format(format: SemiStructuredDataFormat)
  +to_format(format: SemiStructuredDataFormat)
}

class FileDataSet {
  +<<create>>from_format(format: FileFormat)
  +to_format(format: FileFormat)
}
BaseDataSet <|-- StructuredDataSet
BaseDataSet <|-- SemiStructuredDataSet
BaseDataSet <|-- FileDataSet

@enduml
