@startuml
' Definition for ScorerInterface
interface ScorerInterface {
  {abstract} score(): dict[str, float]
}

class ClassificationScorer implements ScorerInterface {
  Precision: float
  Recall: float
  F1_Score: float
  CrossEntropy: float
  score()
}

class RegressionScorer implements ScorerInterface {
  MSE: float
  score()
}

ScorerInterface <|.. ClassificationScorer
ScorerInterface <|.. RegressionScorer

' Definition for EstimatorInterface
interface EstimatorInterface {
  #data: DataSetInterface
  #scorer: ScorerInterface
  {abstract} fit()
  {abstract} predict()
}

class SVMClassifier implements EstimatorInterface {
  fit()
  predict()
  scorer: ClassificationScorer
}

class XGBoostClassifier implements EstimatorInterface {
  fit()
  predict()
  scorer: ClassificationScorer
}

class NNClassifier implements EstimatorInterface {
  fit()
  predict()
  scorer: ClassificationScorer
}

class ElasticNetRegressor implements EstimatorInterface {
  fit()
  predict()
  scorer: RegressionScorer
}

class XGBoostRegressor implements EstimatorInterface {
  fit()
  predict()
  scorer: RegressionScorer
}

EstimatorInterface <|.. SVMClassifier
EstimatorInterface <|.. XGBoostClassifier
EstimatorInterface <|.. NNClassifier
EstimatorInterface <|.. ElasticNetRegressor
EstimatorInterface <|.. XGBoostRegressor
EstimatorInterface "1" *-- "1" ScorerInterface: has a
EstimatorInterface "1" *-- "1" DataSetInterface: has a
@enduml
